---
name: Release

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "v*.*.*"

jobs:
  github:
    name: GitHub
    uses: fabasoad/reusable-workflows/.github/workflows/wf-github-release.yml@5ebe0938b8d8ef97bbb051004c511ba78449a866 # main
    permissions:
      contents: write
